.Dd October 11, 2018
.Dt RLCMP 1
.Sh NAME
.Nm rlcmp
.Nd recursive file compare
.Sh SYNOPSIS
.Nm
.Op OPTIONS
.Op Fl d Ar depth
.Op Fl Fl
.Ar file1
.Ar file2
.Sh DESCRIPTION
.Dq Nm
means
.Do recursive symbolic link Xr cmp 1 Dc .
Compared to
.Xr diff 1
which always follows symbolic links,
.Nm
is intended for a recursive directory compare which never
follows symbolic links.
.Pp
.Nm
stops a file compare when the first difference is found.
It acts on files like a very simple version of
.Xr cmp 1 .
.
.Sh OPTIONS
.
.Bl -tag -width ".It Fl d Ar depth"
.
.It Fl Fl
.
Treat following arguments as filenames even if they begin with
.Sq Fl .
.
.It Fl A
.
Same as option
.Fl aDL .
.
.It Fl a
.
Same as option
.Fl gmtu .
.
.It Fl C
.
Don't compare file contents.
.
.It Fl D
.
When comparing file permissions with
.Fl m
ignore permissions of directories.
.
.It Fl d Ar depth
.
Limit recursion
.Ar depth .
A
.Ar depth
of
.Li 0
means that directories are only entered when they are given as a command
line argument.
.
.It Fl E
.
Write non-error messages to stderr instead of stdout.
.
.It Fl e
.
Exit on first error or difference found.
.
.It Fl g
.
Compare file group.
.
.It Fl H
.
Follow symbolic links listed on the command line.
.
.It Fl L
.
When comparing the modification time with
.Fl t
ignore modification time of symbolic links.
.
.It Fl M Ar n
.
Ignore files which are in one directory tree only
(treat them as equal).
Argument
.Ar n
can be:
.Pp
. Bl -tag -width 1n -compact
. It 0
Ignore missing files in both directory trees.
. It 1
Ignore missing files in first tree.
. It 2
Ignore missing files in second tree.
. El
.
.It Fl m
.
Compare file permissions (except for symbolic links).
.
.It Fl o
.
Report files which
.Em are
only in one directory tree (default of
.Xr diff 1 )
instead of reporting files which are
.Em not
found.
.
.It Fl p
.
Output progress information:
Every ten seconds print the elapsed wall time,
the number of processed files and bytes,
and the currently compared file.
.
.It Fl q
.
Quiet operation, only set exit status.
.
.It Fl s
.
Output summary:
Print elapsed wall time, number of files and bytes processed.
.
.It Fl t
.
Compare modification time (except for directories).
.
.It Fl u
.
Compare file owner.
.
.It Fl V
.
Print version and exit.
.
.It Fl W
.
Debug flag.
Must no be used.
.
.El
.Sh EXIT STATUS
.Nm
exits 0 if no difference is found,
1 on a difference,
and 2 if an error occurs.
.Sh SEE ALSO
.Xr diff 1 ,
.Xr cmp 1
